#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AnylineXamarinApp.Resource", IsApplication=true)]

namespace AnylineXamarinApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int example_activity_classes = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int example_activity_names = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int beep_on_result = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int blink_animation_on_result = 2130771976;
			
			// aapt resource value: 0x7f010030
			public const int camera_id = 2130772016;
			
			// aapt resource value: 0x7f010009
			public const int cancel_on_result = 2130771977;
			
			// aapt resource value: 0x7f010013
			public const int crop_gravity = 2130771987;
			
			// aapt resource value: 0x7f010018
			public const int cutout_alignment = 2130771992;
			
			// aapt resource value: 0x7f010027
			public const int cutout_crop_offset_x = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int cutout_crop_offset_y = 2130772008;
			
			// aapt resource value: 0x7f010025
			public const int cutout_crop_padding_x = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int cutout_crop_padding_y = 2130772006;
			
			// aapt resource value: 0x7f010024
			public const int cutout_drawable = 2130772004;
			
			// aapt resource value: 0x7f01000a
			public const int cutout_feedback_stroke_color = 2130771978;
			
			// aapt resource value: 0x7f01001b
			public const int cutout_max_height_percent = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int cutout_max_width_percent = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int cutout_offset_x = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int cutout_offset_y = 2130771997;
			
			// aapt resource value: 0x7f010029
			public const int cutout_outside_color = 2130772009;
			
			// aapt resource value: 0x7f010022
			public const int cutout_ratio_from_size_height = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int cutout_ratio_from_size_width = 2130772001;
			
			// aapt resource value: 0x7f010023
			public const int cutout_rect_corner_radius_in_dp = 2130772003;
			
			// aapt resource value: 0x7f010020
			public const int cutout_stroke_color = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int cutout_stroke_width_in_dp = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int cutout_style = 2130771998;
			
			// aapt resource value: 0x7f010019
			public const int cutout_width = 2130771993;
			
			// aapt resource value: 0x7f01002b
			public const int flash_alignment = 2130772011;
			
			// aapt resource value: 0x7f01002e
			public const int flash_image_auto = 2130772014;
			
			// aapt resource value: 0x7f01002d
			public const int flash_image_off = 2130772013;
			
			// aapt resource value: 0x7f01002c
			public const int flash_image_on = 2130772012;
			
			// aapt resource value: 0x7f01002a
			public const int flash_mode = 2130772010;
			
			// aapt resource value: 0x7f010000
			public const int overlay_drawable = 2130771968;
			
			// aapt resource value: 0x7f010015
			public const int overlay_height = 2130771989;
			
			// aapt resource value: 0x7f010001
			public const int overlay_outside_color = 2130771969;
			
			// aapt resource value: 0x7f010014
			public const int overlay_width = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int overlay_x = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int overlay_y = 2130771991;
			
			// aapt resource value: 0x7f010002
			public const int preferred_picture_height = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int preferred_picture_width = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int preferred_preview_height = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int preferred_preview_width = 2130771973;
			
			// aapt resource value: 0x7f01002f
			public const int show_fps = 2130772015;
			
			// aapt resource value: 0x7f010007
			public const int vibrate_on_result = 2130771975;
			
			// aapt resource value: 0x7f010011
			public const int visual_feedback_animation_duration = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int visual_feedback_animation_style = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int visual_feedback_corner_radius_in_dp = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int visual_feedback_fill_color = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int visual_feedback_redraw_timeout = 2130771986;
			
			// aapt resource value: 0x7f01000c
			public const int visual_feedback_stroke_color = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int visual_feedback_stroke_width_in_dp = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int visual_feedback_style = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int anyline_logo_white = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bottle_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flash_control_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flash_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int flash_icon_auto = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int flash_icon_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gift_card_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iban_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_barcode = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_card = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_energy = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_energy_old = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_launcher = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_mrz = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int license_plate_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int passport_background = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070019
			public const int any = 2131165209;
			
			// aapt resource value: 0x7f070012
			public const int auto = 2131165202;
			
			// aapt resource value: 0x7f07001a
			public const int back = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int barcode_scan_view = 2131165212;
			
			// aapt resource value: 0x7f070004
			public const int blink = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int bottom = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int bottom_half = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int bottom_left = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int bottom_right = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int center = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int center_vertically = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int contour_point = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int contour_rect = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int contour_underline = 2131165186;
			
			// aapt resource value: 0x7f07001f
			public const int document_scan_view = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int energy_scan_view = 2131165219;
			
			// aapt resource value: 0x7f07001b
			public const int front = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int full_image = 2131165217;
			
			// aapt resource value: 0x7f070011
			public const int image = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int image_result = 2131165216;
			
			// aapt resource value: 0x7f070005
			public const int kitt = 2131165189;
			
			// aapt resource value: 0x7f070027
			public const int listView = 2131165223;
			
			// aapt resource value: 0x7f070033
			public const int main_layout = 2131165235;
			
			// aapt resource value: 0x7f070013
			public const int manual = 2131165203;
			
			// aapt resource value: 0x7f070029
			public const int mrz_result = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int mrz_scan_view = 2131165224;
			
			// aapt resource value: 0x7f070014
			public const int none = 2131165204;
			
			// aapt resource value: 0x7f070034
			public const int ocr_scan_view = 2131165236;
			
			// aapt resource value: 0x7f070006
			public const int pulse = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int pulse_random = 2131165191;
			
			// aapt resource value: 0x7f070024
			public const int radio_button_header = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int radio_group = 2131165221;
			
			// aapt resource value: 0x7f070003
			public const int rect = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int resize = 2131165192;
			
			// aapt resource value: 0x7f070035
			public const int result_background = 2131165237;
			
			// aapt resource value: 0x7f070022
			public const int root = 2131165218;
			
			// aapt resource value: 0x7f07001e
			public const int text = 2131165214;
			
			// aapt resource value: 0x7f07002b
			public const int text_country_code_national = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int text_day_of_birth = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int text_expiration_date = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int text_given_names = 2131165230;
			
			// aapt resource value: 0x7f070032
			public const int text_mrz = 2131165234;
			
			// aapt resource value: 0x7f07002c
			public const int text_number = 2131165228;
			
			// aapt resource value: 0x7f07001d
			public const int text_result = 2131165213;
			
			// aapt resource value: 0x7f070031
			public const int text_sex = 2131165233;
			
			// aapt resource value: 0x7f07002d
			public const int text_surnames = 2131165229;
			
			// aapt resource value: 0x7f07002a
			public const int text_type = 2131165226;
			
			// aapt resource value: 0x7f07000d
			public const int top = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int top_half = 2131165200;
			
			// aapt resource value: 0x7f070017
			public const int top_left = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int top_right = 2131165208;
			
			// aapt resource value: 0x7f070009
			public const int traverse_multi = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int traverse_single = 2131165194;
			
			// aapt resource value: 0x7f070026
			public const int view_flash_placeholder = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarcodeActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DialogResult = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DocumentActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EnergyActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MrzActivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MrzResult = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OCRActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OCRResult = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040016
			public const int analog_meter_7 = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int analog_meter_white = 2130968597;
			
			// aapt resource value: 0x7f040023
			public const int category_barcodes = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int category_documents = 2130968612;
			
			// aapt resource value: 0x7f040020
			public const int category_energy = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int category_fintech = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int category_identification = 2130968609;
			
			// aapt resource value: 0x7f040025
			public const int category_loyality = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int category_others = 2130968614;
			
			// aapt resource value: 0x7f040012
			public const int electric_meter = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int electric_meter_5 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int electric_meter_6 = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int flash_auto = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int flash_off = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int flash_on = 2130968578;
			
			// aapt resource value: 0x7f040017
			public const int gas_4 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int gas_5 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int gas_6 = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int gas_7 = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int heat_meter_4_3 = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int heat_meter_5_3 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int heat_meter_6_3 = 2130968607;
			
			// aapt resource value: 0x7f040004
			public const int scan_analog_electric_meter = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int scan_analog_gas_meter = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int scan_analog_water_meter = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int scan_barcode = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int scan_bottlecaps = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int scan_digital_meter = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int scan_document = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int scan_heat_meter = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int scan_iban = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int scan_license_plates = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int scan_license_plates_austria = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int scan_license_plates_germany = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int scan_mrz = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int scan_voucher_code = 2130968588;
			
			// aapt resource value: 0x7f04001c
			public const int water_black = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int water_white = 2130968603;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MrzResultMrzText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MrzResultText = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AnylineBaseModuleView = new int[]
			{
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int AnylineBaseModuleView_beep_on_result = 0;
			
			// aapt resource value: 2
			public const int AnylineBaseModuleView_blink_animation_on_result = 2;
			
			// aapt resource value: 3
			public const int AnylineBaseModuleView_cancel_on_result = 3;
			
			// aapt resource value: 4
			public const int AnylineBaseModuleView_cutout_feedback_stroke_color = 4;
			
			// aapt resource value: 1
			public const int AnylineBaseModuleView_vibrate_on_result = 1;
			
			// aapt resource value: 11
			public const int AnylineBaseModuleView_visual_feedback_animation_duration = 11;
			
			// aapt resource value: 10
			public const int AnylineBaseModuleView_visual_feedback_animation_style = 10;
			
			// aapt resource value: 9
			public const int AnylineBaseModuleView_visual_feedback_corner_radius_in_dp = 9;
			
			// aapt resource value: 8
			public const int AnylineBaseModuleView_visual_feedback_fill_color = 8;
			
			// aapt resource value: 12
			public const int AnylineBaseModuleView_visual_feedback_redraw_timeout = 12;
			
			// aapt resource value: 6
			public const int AnylineBaseModuleView_visual_feedback_stroke_color = 6;
			
			// aapt resource value: 7
			public const int AnylineBaseModuleView_visual_feedback_stroke_width_in_dp = 7;
			
			// aapt resource value: 5
			public const int AnylineBaseModuleView_visual_feedback_style = 5;
			
			public static int[] AnylineCameraView = new int[]
			{
					2130771968,
					2130771969,
					2130771972,
					2130771973,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 4
			public const int AnylineCameraView_crop_gravity = 4;
			
			// aapt resource value: 0
			public const int AnylineCameraView_overlay_drawable = 0;
			
			// aapt resource value: 6
			public const int AnylineCameraView_overlay_height = 6;
			
			// aapt resource value: 1
			public const int AnylineCameraView_overlay_outside_color = 1;
			
			// aapt resource value: 5
			public const int AnylineCameraView_overlay_width = 5;
			
			// aapt resource value: 7
			public const int AnylineCameraView_overlay_x = 7;
			
			// aapt resource value: 8
			public const int AnylineCameraView_overlay_y = 8;
			
			// aapt resource value: 2
			public const int AnylineCameraView_preferred_preview_height = 2;
			
			// aapt resource value: 3
			public const int AnylineCameraView_preferred_preview_width = 3;
			
			public static int[] AnylineView = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014};
			
			// aapt resource value: 4
			public const int AnylineView_cutout_alignment = 4;
			
			// aapt resource value: 19
			public const int AnylineView_cutout_crop_offset_x = 19;
			
			// aapt resource value: 20
			public const int AnylineView_cutout_crop_offset_y = 20;
			
			// aapt resource value: 17
			public const int AnylineView_cutout_crop_padding_x = 17;
			
			// aapt resource value: 18
			public const int AnylineView_cutout_crop_padding_y = 18;
			
			// aapt resource value: 16
			public const int AnylineView_cutout_drawable = 16;
			
			// aapt resource value: 7
			public const int AnylineView_cutout_max_height_percent = 7;
			
			// aapt resource value: 6
			public const int AnylineView_cutout_max_width_percent = 6;
			
			// aapt resource value: 8
			public const int AnylineView_cutout_offset_x = 8;
			
			// aapt resource value: 9
			public const int AnylineView_cutout_offset_y = 9;
			
			// aapt resource value: 21
			public const int AnylineView_cutout_outside_color = 21;
			
			// aapt resource value: 14
			public const int AnylineView_cutout_ratio_from_size_height = 14;
			
			// aapt resource value: 13
			public const int AnylineView_cutout_ratio_from_size_width = 13;
			
			// aapt resource value: 15
			public const int AnylineView_cutout_rect_corner_radius_in_dp = 15;
			
			// aapt resource value: 12
			public const int AnylineView_cutout_stroke_color = 12;
			
			// aapt resource value: 11
			public const int AnylineView_cutout_stroke_width_in_dp = 11;
			
			// aapt resource value: 10
			public const int AnylineView_cutout_style = 10;
			
			// aapt resource value: 5
			public const int AnylineView_cutout_width = 5;
			
			// aapt resource value: 23
			public const int AnylineView_flash_alignment = 23;
			
			// aapt resource value: 26
			public const int AnylineView_flash_image_auto = 26;
			
			// aapt resource value: 25
			public const int AnylineView_flash_image_off = 25;
			
			// aapt resource value: 24
			public const int AnylineView_flash_image_on = 24;
			
			// aapt resource value: 22
			public const int AnylineView_flash_mode = 22;
			
			// aapt resource value: 0
			public const int AnylineView_preferred_picture_height = 0;
			
			// aapt resource value: 1
			public const int AnylineView_preferred_picture_width = 1;
			
			// aapt resource value: 2
			public const int AnylineView_preferred_preview_height = 2;
			
			// aapt resource value: 3
			public const int AnylineView_preferred_preview_width = 3;
			
			public static int[] CameraBridgeViewBase = new int[]
			{
					2130772015,
					2130772016};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			public static int[] OverlayView = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int OverlayView_overlay_drawable = 0;
			
			// aapt resource value: 1
			public const int OverlayView_overlay_outside_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
